# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/users/manabe/2019/auto_drive/lsd/hdl/project/project_1.cache/wt [current_project]
set_property parent.project_path /home/users/manabe/2019/auto_drive/lsd/hdl/project/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/users/manabe/2019/auto_drive/lsd/hdl/project/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv /home/users/manabe/2019/auto_drive/lsd/hdl/atan_calc.sv
read_verilog -library xil_defaultlib {
  /home/users/manabe/2018/lfif/src/hdl/hdmi/ad_csc_1.v
  /home/users/manabe/2018/lfif/src/hdl/hdmi/ad_csc_1_add.v
  /home/users/manabe/2018/lfif/src/hdl/hdmi/ad_csc_1_mul.v
  /home/users/manabe/2018/lfif/src/hdl/hdmi/ad_csc_RGB2CrYCb.v
  /home/users/manabe/2018/lfif/src/hdl/hdmi/ad_ss_444to422.v
  /home/users/manabe/2018/lfif/src/hdl/adv7511_init/adv7511_command.v
  /home/users/manabe/2018/lfif/src/hdl/adv7511_init/adv7511_i2c_init.v
  /home/users/manabe/2018/lfif/src/hdl/adv7511_init/adv7511_write_one.v
  /home/users/manabe/2018/lfif/src/hdl/hdmi/axi_hdmi_tx_core.v
  /home/users/manabe/2018/lfif/src/hdl/hdmi/axi_hdmi_tx_es.v
  /home/users/manabe/2018/lfif/src/hdl/filter/color_conv/bayer_to_rgb.v
  /home/users/manabe/2018/lfif/src/hdl/cam_if/rx/bitslip8.v
  /home/users/manabe/2018/lfif/src/hdl/util/bram_template_with_reset.v
  /home/users/manabe/2018/lfif/src/hdl/cam_if/cam_calibration.v
  /home/users/manabe/2018/lfif/src/hdl/cam_if/rx/cam_if_lvds_rx.v
  /home/users/manabe/2019/auto_drive/lsd/hdl/common/coord_adjuster.v
  /home/users/manabe/2019/auto_drive/lsd/hdl/common/delay.v
  /home/users/manabe/2019/auto_drive/lsd/hdl/common/fifo_dc.v
  /home/users/manabe/2019/auto_drive/lsd/hdl/gaussian.v
  /home/users/manabe/2018/lfif/src/hdl/hdmi/hdmi16_tx.v
  /home/users/manabe/2018/lfif/src/hdl/i2c/i2c_master_write.v
  /home/users/manabe/2019/auto_drive/lsd/hdl/common/ram_dc.v
  /home/users/manabe/2019/auto_drive/lsd/hdl/common/ram_sc.v
  /home/users/manabe/2019/auto_drive/lsd/hdl/common/rgb2ycbcr.v
  /home/users/manabe/2018/lfif/src/hdl/cam_if/rx/serdes_1_to_8_clk_mmcm_s8_sdr.v
  /home/users/manabe/2018/lfif/src/hdl/cam_if/rx/serdes_1_to_8_sdr.v
  /home/users/manabe/2019/auto_drive/lsd/hdl/simple_lsd.v
  /home/users/manabe/2018/lfif/src/hdl/util/srl_template.v
  /home/users/manabe/2019/auto_drive/lsd/hdl/common/stream_patch.v
  /home/users/manabe/2018/lfif/src/hdl/util/sync_dff.v
  /home/users/manabe/2019/auto_drive/lsd/hdl/common/tree_adder.v
  /home/users/manabe/2018/lfif/kc705_simple_lsd/user_filter.v
  /home/users/manabe/2018/lfif/src/hdl/clock/vcxo_clock_manager.v
  /home/users/manabe/2018/lfif/src/device/kc705/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/users/manabe/2019/auto_drive/lsd/hdl/project/project_1.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files /home/users/manabe/2019/auto_drive/lsd/hdl/project/project_1.srcs/constrs_1/new/const.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
