create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz_0_inst/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {testset_inst/fbl_inst/edge_out[0]} {testset_inst/fbl_inst/edge_out[1]} {testset_inst/fbl_inst/edge_out[2]} {testset_inst/fbl_inst/edge_out[3]} {testset_inst/fbl_inst/edge_out[4]} {testset_inst/fbl_inst/edge_out[5]} {testset_inst/fbl_inst/edge_out[6]} {testset_inst/fbl_inst/edge_out[7]} {testset_inst/fbl_inst/edge_out[8]} {testset_inst/fbl_inst/edge_out[9]} {testset_inst/fbl_inst/edge_out[10]} {testset_inst/fbl_inst/edge_out[11]} {testset_inst/fbl_inst/edge_out[12]} {testset_inst/fbl_inst/edge_out[13]} {testset_inst/fbl_inst/edge_out[14]} {testset_inst/fbl_inst/edge_out[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {testset_inst/fbr_inst/edge_out[0]} {testset_inst/fbr_inst/edge_out[1]} {testset_inst/fbr_inst/edge_out[2]} {testset_inst/fbr_inst/edge_out[3]} {testset_inst/fbr_inst/edge_out[4]} {testset_inst/fbr_inst/edge_out[5]} {testset_inst/fbr_inst/edge_out[6]} {testset_inst/fbr_inst/edge_out[7]} {testset_inst/fbr_inst/edge_out[8]} {testset_inst/fbr_inst/edge_out[9]} {testset_inst/fbr_inst/edge_out[10]} {testset_inst/fbr_inst/edge_out[11]} {testset_inst/fbr_inst/edge_out[12]} {testset_inst/fbr_inst/edge_out[13]} {testset_inst/fbr_inst/edge_out[14]} {testset_inst/fbr_inst/edge_out[15]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets xclk_OBUF]
