# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/project/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/project/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/project/ip_repo/pspl_comm_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/project/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/motor/apamod.sv
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/camera/pynq_ov7670_v3/cam_top.sv
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/motor/hoge.sv
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/motor/pwm14.sv
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/camera/pynq_ov7670_v3/sccb_if.sv
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/motor/testset.sv
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/topview/topview2.sv
}
read_verilog -library xil_defaultlib {
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/lsd/common/arctan_calc.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/camera/pynq_ov7670_v3/camera_if.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/motor/clock_gen.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/lsd/common/coord_adjuster.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/lsd/common/delay.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/motor/fbmod_v1.1.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/lsd/common/fifo_dc.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/lsd/gaussian.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/lsd/lsd_output_buffer.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/motor/pbsbf4_Top.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/motor/pbsbf4_renew.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/lsd/common/ram_dc.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/lsd/common/ram_sc.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/lsd/common/rgb2ycbcr_noreal.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/lsd/simple_lsd.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/lsd/common/stream_patch.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/lsd/common/tree_adder.v
  /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/hdl/alltop.v
}
add_files /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/project/project_1/project_1.srcs/sources_1/bd/pspl_comm/pspl_comm.bd
set_property used_in_implementation false [get_files -all /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/project/project_1/project_1.srcs/sources_1/bd/pspl_comm/ip/pspl_comm_processing_system7_0_1/pspl_comm_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/project/project_1/project_1.srcs/sources_1/bd/pspl_comm/ip/pspl_comm_rst_ps7_0_50M_0_1/pspl_comm_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/project/project_1/project_1.srcs/sources_1/bd/pspl_comm/ip/pspl_comm_rst_ps7_0_50M_0_1/pspl_comm_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/project/project_1/project_1.srcs/sources_1/bd/pspl_comm/ip/pspl_comm_rst_ps7_0_50M_0_1/pspl_comm_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/project/project_1/project_1.srcs/sources_1/bd/pspl_comm/ip/pspl_comm_auto_pc_0_1/pspl_comm_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/project/project_1/project_1.srcs/sources_1/bd/pspl_comm/pspl_comm_ooc.xdc]

read_ip -quiet /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/project/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/project/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/project/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/project/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/xdc/camera.xdc
set_property used_in_implementation false [get_files /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/xdc/camera.xdc]

read_xdc /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/xdc/system.xdc
set_property used_in_implementation false [get_files /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/xdc/system.xdc]

read_xdc /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/xdc/PPAM_v3_2.xdc
set_property used_in_implementation false [get_files /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/xdc/PPAM_v3_2.xdc]

read_xdc /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/xdc/target.xdc
set_property used_in_implementation false [get_files /home/users/matsuda/project/Autonomous_Vehicle_Driving/top/src/xdc/target.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top alltop -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef alltop.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file alltop_utilization_synth.rpt -pb alltop_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
