# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-1256-flamingo/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg400-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/users/matsuda/project/Autonomous_Vehicle_Driving/project/project_1/project_1.srcs/sources_1/bd/pspl_comm/ipshared/70cf/hdl
    /home/users/matsuda/project/Autonomous_Vehicle_Driving/project/project_1/project_1.srcs/sources_1/bd/pspl_comm/ipshared/ec67/hdl
  } {
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/motor/apamod.sv
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/camera/pynq_ov7670_v4/cam_top.sv
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/lsd/debouncer_with_synchronizer.sv
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/camera/pynq_ov7670_v4/dpram_mclk.sv
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/motor/hoge.sv
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/lsd/lsd_output_buffer_wp.sv
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/motor/pwm14.sv
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/camera/pynq_ov7670_v4/sccb_if.sv
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/motor/testset.sv
      /home/cad/xilinx-vivado-2018.3/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /home/cad/xilinx-vivado-2018.3/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/users/matsuda/project/Autonomous_Vehicle_Driving/project/project_1/project_1.srcs/sources_1/bd/pspl_comm/ipshared/70cf/hdl
    /home/users/matsuda/project/Autonomous_Vehicle_Driving/project/project_1/project_1.srcs/sources_1/bd/pspl_comm/ipshared/ec67/hdl
  } {
      ./.Xil/Vivado-1256-flamingo/realtime/pspl_comm_processing_system7_0_0_stub.v
      ./.Xil/Vivado-1256-flamingo/realtime/pspl_comm_pspl_comm_0_5_stub.v
      ./.Xil/Vivado-1256-flamingo/realtime/pspl_comm_rst_ps7_0_100M_1_stub.v
      ./.Xil/Vivado-1256-flamingo/realtime/pspl_comm_auto_pc_0_stub.v
      ./.Xil/Vivado-1256-flamingo/realtime/clk_wiz_0_stub.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/project/project_1/project_1.srcs/sources_1/bd/pspl_comm/synth/pspl_comm.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/lsd/common/arctan_calc.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/camera/pynq_ov7670_v4/camera_if.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/motor/clock_gen.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/lsd/common/coord_adjuster.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/lsd/common/delay.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/lsd/common/divider_iter.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/motor/fbmod_v1.1.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/lsd/common/fifo_dc.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/lsd/gaussian.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/motor/pbsbf4_Top.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/motor/pbsbf4_renew.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/project/project_1/project_1.srcs/sources_1/bd/pspl_comm/hdl/pspl_comm_wrapper.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/lsd/common/ram_dc.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/lsd/common/ram_sc.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/lsd/common/rgb2ycbcr_noreal.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/lsd/simple_lsd.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/lsd/common/stream_patch.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/lsd/common/tree_adder.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/lsd/visualizer.v
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/alltop.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/camera/pynq_ov7670_v4/rgb2dvi/ClockGen.vhd
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/camera/pynq_ov7670_v4/rgb2dvi/DVI_Constants.vhd
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/camera/pynq_ov7670_v4/rgb2dvi/OutputSERDES.vhd
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/camera/pynq_ov7670_v4/rgb2dvi/SyncAsync.vhd
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/camera/pynq_ov7670_v4/rgb2dvi/SyncAsyncReset.vhd
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/camera/pynq_ov7670_v4/rgb2dvi/TMDS_Encoder.vhd
      /home/users/matsuda/project/Autonomous_Vehicle_Driving/src/hdl/camera/pynq_ov7670_v4/rgb2dvi/rgb2dvi.vhd
    }
      rt::read_vhdl -lib xpm /home/cad/xilinx-vivado-2018.3/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top alltop
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-1256-flamingo/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
